### ISSUE TITLE
Error while accessing the weapon shop

### ISSUE THREAD

**Issue by RexShack** [qbcore-redm-framework/qbr-shops#4]
fresh build using the latest recipe, when accessing the weapon shop
![Screenshot 2022-04-13 073230](https://user-images.githubusercontent.com/76662933/163114749-25817b50-db49-45af-8324-891547c2001c.jpg)

**Comment by OGReaperx** [comment]
There is no licenses anymore in the db at all, and the shops just haven’t been updated to have those removed, waiting on this to be fixed

**Comment by SenseiSpringroll** [comment]
RegisterNetEvent('qbr-shops:openshop')
AddEventHandler('qbr-shops:openshop', function(shopType, shopName)
    local type = shopType
    local shop = shopName
    local ShopItems = {}
    ShopItems.items = {}
    --exports['qbr-core']:TriggerCallback('qbr-shops:server:getLicenseStatus', function(result)
        ShopItems.label = shop
        --if type == "weapon" then
            --if result then
                --ShopItems.items =  --Config.Products[type]
            --else
                --for i = 1, #Config.Products[type] do
                    --if not Config.Products[type]--[i].requiresLicense then
                        --table.insert(ShopItems.items, --Config.Products[type][i])
                    --end
                --end
            --end
        --else
            ShopItems.items = Config.Products[type]
        --end
        ShopItems.slots = 30
        TriggerServerEvent("inventory:server:OpenInventory", "shop", "Itemshop_"..type, ShopItems) --Review later for visual correction
    --end)
end)

**Comment by centrdev** [comment]
hope it gets resoveld soon

**Comment by RexShack** [comment]
@centrdev temporary fix while they work it out is
replace this on client.lua

```lua
RegisterNetEvent('qbr-shops:openshop')
AddEventHandler('qbr-shops:openshop', function(shopType, shopName)
    local type = shopType
    local shop = shopName
    local ShopItems = {}
    ShopItems.items = {}
    exports['qbr-core']:TriggerCallback('qbr-shops:server:getLicenseStatus', function(result)
        ShopItems.label = shop
        if type == "weapon" then
            if result then
                ShopItems.items =  Config.Products[type]
            else
                for i = 1, #Config.Products[type] do
                    if not Config.Products[type][i].requiresLicense then
                        table.insert(ShopItems.items, Config.Products[type][i])
                    end
                end
            end
        else
            ShopItems.items = Config.Products[type]
        end
        ShopItems.slots = 30
        TriggerServerEvent("inventory:server:OpenInventory", "shop", "Itemshop_"..type, ShopItems) --Review later for visual correction
    end)
end)
```

with this

```lua
RegisterNetEvent('qbr-shops:openshop')
AddEventHandler('qbr-shops:openshop', function(shopType, shopName)
    local type = shopType
    local shop = shopName
    local ShopItems = {}
    ShopItems.items = {}
	ShopItems.label = shop
	ShopItems.items = Config.Products[type]
	ShopItems.slots = 30
	TriggerServerEvent("inventory:server:OpenInventory", "shop", "Itemshop_"..type, ShopItems) --Review later for visual correction
end)
```

**Comment by centrdev** [comment]
awesome, that did it

**Comment by ansljeremy** [comment]
Resolved in https://github.com/qbcore-redm-framework/qbr-core/pull/26
